name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * 1-5'  # 8:30 AM CST Mon–Fri (UTC 13:30)
    - cron: '30 21 * * 1-5'  # 4:30 PM CST Mon–Fri (UTC 21:30)

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install Newman and html-extra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with Newman
        run: |
          newman run 'Inwarranty-flow Collection.postman_collection.json' \
            -e 'QA.postman_environment.json' \
            -d 'testData.csv' \
            -r cli,htmlextra
