name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * 1-5'  # 8:30 AM CST Mon–Fri (UTC 13:30)
    - cron: '30 21 * * 1-5'  # 4:30 PM CST Mon–Fri (UTC 21:30)

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and Html extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          newman run 'Inwarranty-flow Collection.postman_collection.json' \
            -e 'QA.postman_environment.json' \
            -d 'testData.csv' \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always()  # upload report artifact regardless of test result
        uses: actions/upload-artifact@v4
        with:
          name: Newman Report
          path: newman/*.html

      - name: Publish HTML report via GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow test execution notification
          to: dipikazope27@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,
            Phoenix Inwarranty flow test has been executed. You can view the report at:
            https://dipikaz.github.io/Pheonix-Inwarranty-flow-/
